### ISSUE TITLE
pins at arduino

### ISSUE THREAD

**Issue by jonnyfalconetti** [AsherGlick/Charliecube#2]
hey there, great projekt.
can you please tell me which group is connected to which pin at the arduino?
my hardwarepart is ready but it's hard to find the right pins...

regards
jonny

**Comment by jonnyfalconetti** [comment]
could you please tell us which pin is connected to which group?
i'm not the only one with this problem:
http://hackaday.com/2012/01/07/minimalist-rgb-led-cube-has-a-very-short-bom/#comments
(comments)

thanks

**Comment by AsherGlick** [comment]
I apologise for not getting to this sooner. It has now been fixed and can be viewed on the website [aglick.com/charliecube](http://aglick.com/charliecube)
the wires are colour coded and there is a chart matching the colours to the Arduino pins and the AVR pins

**Comment by jonnyfalconetti** [comment]
thanks a lot :)

**Comment by jonnyfalconetti** [comment]
you've changed the entire wiring layout, don't you?

**Comment by AsherGlick** [comment]
I have not changed the entire layout, I have changed the colours of the wire and the fourth section is rotated 90 degrees however the old wiring scheme will work as well. I changed the colours so that they would better match up with the ID colours in the table. If you would like to see the old diagrams you can go to [aglick.com/charliecubeold.html](http://aglick.com/charliecubeold.html). If the documentation is still too confusing I will continue to work on it until it makes sense.

**Comment by jonnyfalconetti** [comment]
works like a charme with the new wiring, thanks a lot :)

http://www.youtube.com/watch?v=eaxJQpWh0MY
