### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sbliven** [AsherGlick/Charliecube#4]
The header of niceTimer.h says that "all of the code is under a BSD-like licence so feel free to take it an use it for whatever you want." This is quite vague, but could refer to the 2-clause FreeBSD license. In cubeplex.h it says 'written by Asher Glick (aglick@aglick.com) all rights reserved," which would seem to contradict the previous BSD license.

Could you please clarify which license the code uses? An official LICENSE file with some legal text would be best. Thanks for making you code public on github!

**Comment by AsherGlick** [comment]
Wow, I love seeing the rookie mistakes I made in some of my old code. I am beginning to work on a new version of this code, with support for the Arduino Leonardo and Arduino Mega, as well as more color mixing capabilities. The source is all under the BSD licence now, I also went on a slight ego trip and added my name in awesome letters.
Fixed with f3f4dc6e267bc4715702d7197dcb509595128e3f

**Comment by sbliven** [comment]
Thanks! In that case I'll upload my modifications.
